### ISSUE TITLE
Start hazelcast with proper module access when running on JDK9+

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast-command-line#10]
When java runtime version is 9+, the tool should take care of adding the required module exports/opens. Currently `hazelcast-member start` with JDK9 logs:

```
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
```

**Comment by alparslanavci** [comment]
Provided with the new implementation.

**Comment by winne42** [comment]
@alparslanavci could you please provide more hints what the "new implementation" is? From which released version or unreleased commit on are the options set?

**Comment by alparslanavci** [comment]
@winne42 The new implementation starts from [v4.2020.08](https://github.com/hazelcast/hazelcast-command-line/releases/tag/v4.2020.08) but we recommend downloading [the latest version](https://github.com/hazelcast/hazelcast-command-line/releases/tag/v4.2020.12). Please check the readme for different installation options.
