### ISSUE TITLE
`Ambigous command` message should show number of running, stopped members

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast-command-line#2]
After I started many members and kill them all. Even there is no live member process, i'm getting Error: Ambiguous command: 5 Hazelcast members when i try to run command: hazelcast-member logs

▶ hazelcast-member logs
Error: Ambiguous command: 5 Hazelcast members

▶ jps
321
5187 Jps
727 RemoteMavenServer

**Comment by ahmetmircik** [comment]
My first impression was `the message is wrong` but based on your explanation, now it makes sense. Thanks.

But if an enhancement is asked ever, the printed message alternatives can be:
`Error: Ambiguous command: PID of a member required` 
 or 
`Error: Ambiguous command: 5 Hazelcast members (running 3, stopped 2)`

**Comment by googlielmo** [comment]
Closing this, as it doesn't apply to the new command line command anyway :-)
