### ISSUE TITLE
Add Download Source to Pardot ID

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-command-line#4]
The file `hazelcast-download.properties` should contain value like: `hazelcastDownloadId=tool` or something similar.

**Comment by alparslanavci** [comment]
@leszko This issue belongs to the old implementation, but does it also needed in the new one? If so, can you please explain it further?

**Comment by leszko** [comment]
Hazelcast sends the content of `hazelcast-download.properties` to Call Home API. So if you add a file `hazelcast-download.properties` with the content `hazelcastDownloadId=CLI` or `hazelcastDownloadId=tool`, then we'll be able to get the usage metrics for CLI from the Call Home Storage.

Here's how it's done for our Docker image: https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-oss/Dockerfile#L46

**Comment by alparslanavci** [comment]
Fixed by #77
