### ISSUE TITLE
JCache support missing

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast-command-line#64]
The distribution does not bundle `cache-api` artifact, so JCache support is missing.

Trying to create a JCache cache from a client connecting to a `hz start`-ed member results in:
```
Exception in thread "main" com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: javax/cache/configuration/CompleteConfiguration
	at com.hazelcast.client.UndefinedErrorCodeException.wrap(UndefinedErrorCodeException.java:55)
	at com.hazelcast.client.UndefinedErrorCodeException.wrap(UndefinedErrorCodeException.java:26)
....
```

Since one is currently not allowed to pass additional class path entries on the cmd line, there is no workaround.

**Comment by alparslanavci** [comment]
Yes, we can think of adding the `cache-api` artifact by default. But there is a workaround, you can add additional class path entries when starting a member: 

```
hz start -j /path/to/classes
```
By using this, I managed to use JCache cache from a connected client.

**Comment by vbekiaris** [comment]
Great, I wasn't aware of `hz start -j` (and obviously didn't run `hz start -h` 😄 ). I prepared a small PR (#65) that adds this info to README; currently it only mentions you are not allowed to add classpath java options and that statement misled me to believe it was not possible.

**Comment by Holmistr** [comment]
@alparslanavci I think adding the `cache-api` artifact by default makes sense. We should work out of the box as much as possible.

**Comment by alparslanavci** [comment]
@Holmistr this will change the default Hazelcast distribution structure. Do you know why we haven't added `cache-api` to the default Hazelcast package at all? I think it will make sense if we update the structure over there.

**Comment by Holmistr** [comment]
@alparslanavci I think the `cache-api` dependency is shaded inside the `hazelcast-all` JAR. @vbekiaris correct me if I'm wrong.

**Comment by vbekiaris** [comment]
`cache-api` is actually not included in `hazelcast-all`

**Comment by alparslanavci** [comment]
yes, it is not included in any Hazelcast distribution. See here: https://docs.hazelcast.org/docs/latest/manual/html-single/#setting-up-your-application

**Comment by Holmistr** [comment]
@vbekiaris In that case, do you know the answer to @alparslanavci 's previous question? https://github.com/hazelcast/hazelcast-command-line/issues/64#issuecomment-702628868

**Comment by vbekiaris** [comment]
>  Do you know why we haven't added cache-api to the default Hazelcast package at all?

not really sure about the original reasons why that is the case. My guess is that since Hazelcast predates JCache 1.0.0 and JCache is just one of many Hazelcast features, why force-add the JCache dependency for all users? 

That said, my original issue was lack of `cache-api` dependency in combination with what I originally thought was inability to add JARs to classpath. Since adding classes / JARs to classpath is possible, I am happy to close this issue.
