### ISSUE TITLE
failed start does not report back on command line

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-command-line#8]
When starting a member fail-fast errors should be reported.

For example the java process exited but this was not reported back to the command line.

Could we wait somehow for confirmation that a cluster has been joined?

See screenshot...

![screenshot from 2018-11-22 10-54-21](https://user-images.githubusercontent.com/1588244/48898759-8701db00-ee45-11e8-8610-0d384ca1ca4f.png)

**Comment by alparslanavci** [comment]
Not applicable to the new implementation.
