### ISSUE TITLE
Option to specify MC config

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-command-line#80]
The tool allows to specify HZ Member config, but it does not allow to specify MC config. It's needed when I want to connect MC to a cluster running elsewhere.

**Comment by alparslanavci** [comment]
@jerrinot I couldn't understand the issue here clearly, which MC config do you mean?

**Comment by jerrinot** [comment]
I was under an impression you could supply a client configuration to MC. but perhaps I have mistaken this for the old Jet MC. Thinking about this it does not make much sense. Sorry for a bad issue.
